# Generated by Django 5.1.3 on 2024-12-02 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cc_user', models.IntegerField(default=0)),
                ('user_type', models.CharField(choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('professional_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
