# Generated by Django 5.1.3 on 2024-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cc_user',
            field=models.IntegerField(default=0),
        ),
    ]
