apiVersion: v1
kind: Pod
metadata:
  name: api-gateway-pod
  labels:
    app: api-gateway
  annotations:
    prometheus.io/scrape: "true"       # Habilita la recolección de métricas
    prometheus.io/port: "8001"         # Puerto donde se expone el endpoint /metrics
    prometheus.io/path: "/metrics"     # Ruta del endpoint para las métricas
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube-m02 # Nodo deseado
                  - minikube-m03 # Nodo alternativo
  containers:
    - name: api-gateway-container
      image: dylanfarkas/api_gateway:latest
      ports:
        - containerPort: 5000
        - containerPort: 8001 # Puerto para métricas
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001 # Exponer puerto de métricas
  type: ClusterIP
