apiVersion: v1
kind: Pod
metadata:
  name: auth-pod
  labels:
    app: auth
spec:
  containers:
    - name: auth-container
      image: ervincaravaliibarra/auth:latest
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
