apiVersion: v1
kind: Pod
metadata:
  name: gestion-login-pod
  labels:
    app: gestion-login
spec:
  containers:
    - name: gestion-login-container
      image: yenreh/gestion_login:latest
      ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-login-service
spec:
  selector:
    app: gestion-login
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP