apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-2
  labels:
    app: redis-2
spec:
  containers:
    - name: redis-2-container
      image: redis:latest
      ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service-2
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-2