apiVersion: v1
kind: Pod
metadata:
  name: microfrontend-pod
  labels:
    app: microfrontend
spec:
  containers:
  - name: microfrontend-container
    image: yenreh/microfrontend:latest
    ports:
    - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: microfrontend-service
spec:
  selector:
    app: microfrontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
  type: ClusterIP