apiVersion: v1
kind: Pod
metadata:
  name: comunicaciontiemporeal
  labels:
    app: comunicaciontiemporeal
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube-m02 # Nodo permitido
                  - minikube-m03 # Nodo permitido
  containers:
    - name: comunicaciontiemporeal
      image: ervincaravaliibarra/comunicaciontiemporeal:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: comunicaciontiemporeal
spec:
  selector:
    app: comunicaciontiemporeal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
