apiVersion: v1
kind: Pod
metadata:
  name: gestion-usuarios-pod
  labels:
    app: gestion-usuarios
spec:
  containers:
    - name: gestion-usuarios-container
      image: ervincaravaliibarra/gestion_usuarios
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: gestion-usuarios-service
spec:
  selector:
    app: gestion-usuarios
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

