apiVersion: v1
kind: Pod
metadata:
  name: gestion-citas-medicas-pod
  labels:
    app: gestion-citas-medicas
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube-m02 # Nodo permitido
                  - minikube-m03 # Nodo permitido
  containers:
    - name: gestion-citas-medicas-container
      image: dylanfarkas/gestion_citas_medicas
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-citas-medicas-service
spec:
  selector:
    app: gestion-citas-medicas
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer


